apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: charts/argo-cd
    repoURL: https://github.com/sebcih/finaltest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
