apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-configs
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-configs
    repoURL: https://github.com/sebcih/finaltest.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
