argo-cd:
  global:
    image:
      tag: v2.2.7
  dex:
    enabled: true
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
